export const SET_SELECTED_SPORT_LIST = "SET_SELECTED_SPORT_LIST";
export const SET_CURRENT_STEP = "SET_CURRENT_STEP";
export const SET_SPORT_LIST_DATA = "SET_SPORT_LIST_DATA";
export const SET_PARTNER_TYPE_LIST_DATA = "SET_PARTNER_TYPE_LIST_DATA";
export const SET_SELECTED_PARTNER_TYPE_LIST = "SET_SELECTED_PARTNER_TYPE_LIST";
export const SET_SELECTED_LOCATION = "SET_SELECTED_LOCATION";
export const SET_LOCATION_LIST = "SET_LOCATION_LIST";

export const SET_PARTNER_LIST_DATA = "SET_PARTNER_LIST_DATA";
export const RESET_STATE = "RESET_STATE";
export const SHOW_MESSAGE_LOCATION_EMPTY = "SHOW_MESSAGE_LOCATION_EMPTY";
export const SET_COACH_DETAILS_DATA = "SET_COACH_DETAILS_DATA";

export default {
  SET_SELECTED_SPORT_LIST,
  SET_CURRENT_STEP,
  SET_SPORT_LIST_DATA,
  SET_PARTNER_TYPE_LIST_DATA,
  SET_SELECTED_PARTNER_TYPE_LIST,
  SET_SELECTED_LOCATION,
  SET_LOCATION_LIST,
  SET_PARTNER_LIST_DATA,
  RESET_STATE,
  SHOW_MESSAGE_LOCATION_EMPTY,
  SET_COACH_DETAILS_DATA
};
