export const PRODUCT_LIST = "PRODUCT_LIST";
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST";
export const SET_BLOG_LIST = "SET_BLOG_LIST";
export const SET_RECIPIE_LIST = "SET_RECIPIE_LIST";
export const SET_FRUIT_DETAIL_DATA = "SET_FRUIT_DETAIL_DATA";
export const SET_FOOTER_MENU_LIST = "SET_FOOTER_MENU_LIST";
export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";
export const SET_NUTRIENT_DATA = "SET_NUTRIENT_DATA";
export const SET_TRACE_DATA = "SET_TRACE_DATA";
export const SET_BLOG_DETAIL_DATA = "SET_BLOG_DETAIL_DATA";
export const SET_RECIPIE_DETAIL_DATA = "SET_RECIPIE_DETAIL_DATA";
export const SET_BLOG_SIMILAR_DATA = "SET_BLOG_SIMILAR_DATA";
export const SET_RECIPIE_SIMILAR_DATA = "SET_RECIPIE_SIMILAR_DATA";
export const SET_FOLLOWS_US_DATA = 'SET_FOLLOWS_US_DATA';
export const SET_NUTRIENTS_POPUP_INFO = 'SET_NUTRIENTS_POPUP_INFO';
export const SET_OTHER_USES_DATA = 'SET_OTHER_USES_DATA';
export const SET_BLOG_FILTER_DATA = 'SET_BLOG_FILTER_DATA';
export const SELECTED_MENU = 'SELECTED_MENU';
export const SET_OWNER_DETAIL_DATA = 'SET_OWNER_DETAIL_DATA';

export default {
  PRODUCT_LIST,
  SET_PRODUCT_LIST,
  SET_BLOG_LIST,
  SET_RECIPIE_LIST,
  SET_FRUIT_DETAIL_DATA,
  SET_FOOTER_MENU_LIST,
  SET_CATEGORY_LIST,
  SET_NUTRIENT_DATA,
  SET_TRACE_DATA,
  SET_BLOG_DETAIL_DATA,
  SET_RECIPIE_DETAIL_DATA,
  SET_BLOG_SIMILAR_DATA,
  SET_RECIPIE_SIMILAR_DATA,
  SET_FOLLOWS_US_DATA,
  SET_NUTRIENTS_POPUP_INFO,
  SET_OTHER_USES_DATA,
  SET_BLOG_FILTER_DATA,
  SELECTED_MENU,
  SET_OWNER_DETAIL_DATA
};
